version: "3"

services:
  redis-server:
    image: redis
#    container_name: redis-server
#    ports:
#      - "6379:6379"
#    restart: always
#    networks:
#      - backend
  spring-app:
    build: .
#    container_name: spring-app
    depends_on:
      - redis-server
    ports:
      - "7003:7003"
#    restart: always
#    networks:
#      - backend
#volumes:
#  redis-data:
#networks:
#  backend: