version: "3"

services:
  redis-server:
    image: redis
    container_name: redis-server
    restart: always
    volumes:
      - redis-data:/data
  spring-app:
    build: .
    depends_on:
      - redis-server
    ports:
      - "7003:7003"
    restart: always
volumes:
  redis-data: